### ISSUE TITLE
[BROKEN] Homebrew installation

### ISSUE THREAD

**Issue by dhilipsiva** [kura/go-bash-completion#1]
<img width="467" alt="screen shot 2016-01-13 at 21 56 34" src="https://cloud.githubusercontent.com/assets/502170/12300245/99e0fe68-ba40-11e5-946a-cb0d468da0e7.png">

**Comment by asfaltboy** [comment]
Oddly github doesn't show a trace of `go-completion` in Homebrew/homebrew-completions.

@kura shall I submit a PR, something along these lines ?

``` ruby
class GoCompletion < Formula
  desc "Bash and Zsh completion for Go CLI"
  homepage "https://github.com/kura/go-bash-completion"
  url "https://github.com/kura/go-bash-completion.git",
    :revision => "f2d3af2bd51d09087b2dab57f21455b51e174792"
  version "1"
  head "https://raw.githubusercontent.com/kura/go-bash-completion.git"

  bottle :unneeded

  def install
    bash_completion.install "etc/bash_completion.d/go" => "grunt"
  end

  test do
    assert_match "-F _go",
      shell_output("source #{bash_completion}/go && complete -p go")
  end
end
```

**Comment by kura** [comment]
If you'd like to, sure. I don't use Homebrew so anything related to that, feel free to do whatever you guys want with it. :)
