### ISSUE TITLE
Fedora installation

### ISSUE THREAD

**Issue by DaKine23** [kura/go-bash-completion#4]
If someone wants to install this into a Fedora system he needs to copy the "go" file to

`/usr/share/bash-completion/completions`

as 

`/etc/bash_completion.d/go`  

is not used by Fedora

**Comment by DylanGraham** [comment]
Hi, this directory *is* used on Fedora:

    $ rpm -qf /etc/bash_completion.d/
    filesystem-3.2-40.fc26.x86_64
    bash-completion-2.6-1.fc26.noarch
